---
- name: install
  unarchive:
    src: filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz
    dest: /opt
    creates: /opt/filebeat-{{ filebeat_version }}-linux-x86_64/filebeat
    owner: root
    group: root
  notify:
    - restart filebeat

- name: create filebeat.service
  template:
    src: filebeat.service.j2
    dest: /etc/systemd/system/filebeat.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart filebeat

- name: create filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /opt/filebeat-{{ filebeat_version }}-linux-x86_64/filebeat.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - restart filebeat

- name: start filebeat
  systemd:
    state: started
    daemon_reload: yes
    name: filebeat.service
