---
- name: restart flannel
  systemd:
    state: restarted
    daemon_reload: yes
    name: flannel.service

- name: restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker.service

- name: configure flannel
  command: >-
    etcdctl
      set /coreos.com/network/config
      '{{ flannel_config | to_json }}'
