---
- name: mkdir
  file:
    path: /opt/flannel-{{ version }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install
  unarchive:
    src: flannel-{{ version }}-linux-amd64.tar.gz
    dest: /opt/flannel-{{ version }}
    creates: /opt/flannel-{{ version }}/flanneld
    owner: root
    group: root
  notify:
    - restart flannel
    - configure flannel

- name: create flannel.service
  template:
    src: flannel.service.j2
    dest: /etc/systemd/system/flannel.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart flannel
    - configure flannel

- name: mkdir
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: docker info
  command: rpm -qi docker
  args:
    warn: False
  register: docker_info

- name: docker 1.12.6 systemd override
  template:
    src: docker-1.12.6.override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  when:
    docker_info.stdout.find("1.12.6") != -1
  notify:
    - restart docker
    - configure flannel

- name: docker 1.6.2 systemd override
  template:
    src: docker.override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  when:
    docker_info.stdout.find("1.6.2") != -1
  notify:
    - restart docker
    - configure flannel

- name: start flannel
  systemd:
    enabled: yes
    state: started
    daemon_reload: yes
    name: flannel.service
